### PR TITLE
Update GNOME runtime and app version

### PR DESCRIPTION
**Pull request by dusansimic**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by dusansimic** [comment]
@johnfactotum a friendly bump 😁. Soon sdk 43 will be released and I'll bump that one too.

**Comment by johnfactotum** [comment]
Thanks! Is WebKitGTK for GTK 4 in 42 or 43? If so, could you make a PR to update it to the latest 2.0.0 release? Unfortunately I can't test it right now.

**Comment by dusansimic** [comment]
Afaik, it should be available in 42. I'll try to build it in the next few days and update this pr so that it bumps the app version too.

**Comment by dusansimic** [comment]
bot, build

**Comment by dusansimic** [comment]
@johnfactotum I've bumped both the runtime version to 43 and the app version to 2.0.0. It seems to work as expected.

**Comment by johnfactotum** [comment]
Thanks a lot!

**Pull request merged**
